---
- hosts: localhost
  connection: local
  gather_facts: False

  vars_prompt:
    - name: "osx_user"
      prompt: "What is the OS X user name to under which to run this playbook?"
      private: no

    - name: "kitchen_path"
      prompt: "Path to the kitchen"
      default: "/opt/kitchen"

  roles:
    - user_checks
    - kitchen
