---
- name: "Vim latest binary via homebrew"
  homebrew: name=vim state=present update_homebrew=yes

- name: "Vim Pathogen Directories"
  file: path=/Users/{{ osx_user }}/{{ item }} state=directory
  with_items:
    - .vim
    - .vim/autoload
    - .vim/bundle

- name: "Vim Pathogen Install"
  get_url: url="https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim"
           dest="/Users/{{ osx_user }}/.vim/autoload/pathogen.vim"

- name: "Vim plugins: Git ones"
  git: repo={{ item.plugin_git_url }}
       dest=/Users/{{ osx_user }}/.vim/bundle/{{ item.plugin_name}}
       update=yes
  with_items:
    - { plugin_git_url: "https://github.com/sjl/gundo.vim.git",
  plugin_name: "gundo.vim" }
    - { plugin_git_url: "https://github.com/Lokaltog/vim-powerline",
  plugin_name: "vim-powerline" }
    - { plugin_git_url: "https://github.com/scrooloose/nerdtree.git",
  plugin_name: "nerdtree" }
    - { plugin_git_url: "https://github.com/elzr/vim-json.git",
  plugin_name: "vim-json" }
    - { plugin_git_url: "https://github.com/nathanaelkane/vim-indent-guides.git",
  plugin_name: "vim-indent-guides" }
    - { plugin_git_url: "https://github.com/scrooloose/syntastic.git",
  plugin_name: "syntastic" }
    - { plugin_git_url: "https://github.com/tpope/vim-fugitive.git",
  plugin_name: "vim-fugitive" }
    - { plugin_git_url: "git@github.com:Townk/vim-autoclose.git",
  plugin_name: "vim-autoclose" }

- name: "VIM Config (~/.vimrc)"
  copy: src=vimrc dest=/Users/{{ osx_user }}/.vimrc

